module.exports = {
  mySidebar: [
    'index',
    {
      type: 'category',
      label: 'Schedule and Job Basics',
      collapsed: true,
      items: [
        'agents-machines',
        'schedules',
//        'practice-create-a-schedule',
        'jobs',
//        'practice-create-a-job',
        'null-jobs',
//        'practice-create-a-null-job',
        'frequency-definition',
//        'practice-create-a-frequency',
        'schedule-build',
//        'practice-build-a-schedule',
        'dependencies',
//        'practice-create-a-job-dependency',
        'tags',
//        'practice-create-a-tag',
      ],
  },
  {
    type: 'category',
    label: 'Operations',
    collapsed: true,
    items: [
      'operational-views',
      'schedule-and-job-status',
      'notification-manager',
      'escalation-manager',
      'logs',    
    ],
  },
  {
    type: 'category',
    label: 'Objects and Components',
    collapsed: true,
    items: [
      'calendars',
//      'practice-calendars',
      'global-properties',
//      'practice-create-a-global-property',
      'events',
//      'practice-create-an-event',
      'resources',
//      'practice-create-a-resource',
      'scripts',
//      'practice-scripts',     
      'thresholds',
//      'practice-create-a-threshold',
    ],
},
{
  type: 'category',
  label: 'Advanced Features',
  collapsed: true,
  items: [
    'subschedules',
//    'practice-subschedules',  
    'file-arrival',
//  'practice-file-arrival',
    'file-movement',
  ],
},
{
  type: 'category',
  label: 'Security',
  collapsed: true,
  items: [
    'user-accounts-and-role-management',
    'privileges',
    'departments',
    'access-codes',
    'common-role-configurations',
  ],
},
  ],
};